basePath: /
definitions:
  organization.OrganizationNew:
    properties:
      email:
        type: string
      name:
        maxLength: 64
        minLength: 1
        type: string
      password:
        minLength: 6
        type: string
      phone:
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    - phone
    type: object
  response.ErrorRes:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  response.SuccessRes:
    properties:
      data: {}
    type: object
host: 0.0.0.0:8080
info:
  contact:
    email: lxx0103@yahoo.com
    name: Lewis
  description: API for go-api.
  title: go-api API
  version: "1.0"
paths:
  /organizations:
    post:
      consumes:
      - application/json
      operationId: "001"
      parameters:
      - description: 组织信息
        in: body
        name: organization_info
        required: true
        schema:
          $ref: '#/definitions/organization.OrganizationNew'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessRes'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorRes'
      summary: 新建组织
      tags:
      - 组织管理
swagger: "2.0"
